# Import all libraries

In [2]:
import sys
from pathlib import Path
import pandas as pd

# Import Function

In [3]:
pd.set_option('display.float_format', lambda x: f'{x:.4f}')

sys.path.append(str(Path('function').resolve()))
from pearson_function import pearson_test

# Load Data

In [4]:
df = pd.read_csv('../../00-dataSource/clean_data_v1.csv')
df.head()

,age,gender,device_hours_per_day,phone_unlocks,notifications_per_day,social_media_mins,study_mins,physical_activity_days,sleep_hours,sleep_quality,stress_level,digital_dependence_score
0,40,female,3.5400,45,561,98,34,7.0000,9.1238,3.3536,6.5933,25.7000
1,27,male,5.6500,100,393,174,102,2.0000,8.8375,2.9081,4.1269,30.1000
2,31,male,8.8700,181,231,595,140,1.0000,6.4867,2.8892,1.4291,40.6000
3,41,female,4.0500,94,268,18,121,4.0000,7.6005,3.0975,4.9955,36.6842
4,26,female,13.0700,199,91,147,60,1.0000,5.1980,2.7861,9.4488,48.4000

## hypothesis between age & stress level

In [5]:
pearson_results = pd.DataFrame([
    pearson_test(df, 'age', 'stress_level'),
])

pearson_results

,Variables,Correlation (r),p-value,Relationship,Decision,Conclusion
0,age vs stress_level,0.0025,0.8845,very weak positive,Fail to reject H0,The relationship between age and stress_level ...

### reflection
Based on the correlation analysis and hypothesis testing, age shows no statistically significant relationship with stress level.

This indicates that age has minimal influence on stress level in this dataset and may be considered a low-impact feature.

## hypothesis between phone_unlocks & stress level

In [6]:
pearson_results = pd.DataFrame([
    pearson_test(df, 'phone_unlocks', 'stress_level'),
])

pearson_results

,Variables,Correlation (r),p-value,Relationship,Decision,Conclusion
0,phone_unlocks vs stress_level,0.2693,0.0000,weak positive,Reject H0,The relationship between phone_unlocks and str...

## hypothesis between notifications_per_day & stress level

In [7]:
pearson_results = pd.DataFrame([
    pearson_test(df, 'notifications_per_day', 'stress_level'),
])

pearson_results

,Variables,Correlation (r),p-value,Relationship,Decision,Conclusion
0,notifications_per_day vs stress_level,0.1684,0.0000,very weak positive,Reject H0,The relationship between notifications_per_day...

## hypothesis between social_media_mins & stress level

In [8]:
pearson_results = pd.DataFrame([
    pearson_test(df, 'social_media_mins', 'stress_level'),
])

pearson_results

,Variables,Correlation (r),p-value,Relationship,Decision,Conclusion
0,social_media_mins vs stress_level,0.0227,0.1793,very weak positive,Fail to reject H0,The relationship between social_media_mins and...

### reflection
Social media usage does not significantly affect stress level individually, but it may still play a role when combined with other factors

In [ ]:
## hypothesis between study_mins & stress level

In [9]:
pearson_results = pd.DataFrame([
    pearson_test(df, 'study_mins', 'stress_level'),
])

pearson_results

,Variables,Correlation (r),p-value,Relationship,Decision,Conclusion
0,study_mins vs stress_level,-0.0050,0.7691,very weak negative,Fail to reject H0,The relationship between study_mins and stress...

### reflection
Based on the correlation analysis and hypothesis testing, study_mins has an extremely weak and statistically insignificant relationship with stress level.

This suggests that study time does not directly affect stress level and is likely not an important individual predictor in this dataset.

## hypothesis between physical_activity_days & stress level

In [10]:
pearson_results = pd.DataFrame([
    pearson_test(df, 'physical_activity_days', 'stress_level'),
])

pearson_results

,Variables,Correlation (r),p-value,Relationship,Decision,Conclusion
0,physical_activity_days vs stress_level,-0.0481,0.0044,very weak negative,Reject H0,The relationship between physical_activity_day...

## hypothesis between sleep_quality & stress level

In [11]:
pearson_results = pd.DataFrame([
    pearson_test(df, 'sleep_quality', 'stress_level'),
])

pearson_results

,Variables,Correlation (r),p-value,Relationship,Decision,Conclusion
0,sleep_quality vs stress_level,-0.1923,0.0000,very weak negative,Reject H0,The relationship between sleep_quality and str...

## hypothesis between digital_dependence_score & stress level

In [12]:
pearson_results = pd.DataFrame([
    pearson_test(df, 'digital_dependence_score', 'stress_level'),
])

pearson_results

,Variables,Correlation (r),p-value,Relationship,Decision,Conclusion
0,digital_dependence_score vs stress_level,0.3465,0.0000,weak positive,Reject H0,The relationship between digital_dependence_sc...