# Import all libraries

In [1]:
import sys
from pathlib import Path
import pandas as pd

# Import Function

In [2]:
pd.set_option('display.float_format', lambda x: f'{x:.4f}')

sys.path.append(str(Path('function').resolve()))
from pearson_function import pearson_test

# EDA-Based Assumption
Based on the EDA results, **sleep hours** show a negative relationship with **stress level**.
The study aims to test whether sleep hours significantly affect stress level by using Pearson correlation analysis and hypothesis testing.

# Load Data

In [3]:
df = pd.read_csv('../../00-dataSource/clean_data_v1.csv')
df.head()

,age,gender,education_level,device_hours_per_day,phone_unlocks,notifications_per_day,social_media_mins,study_mins,physical_activity_days,sleep_hours,sleep_quality,stress_level,productivity_score
0,40,female,high school,3.5400,45,561,98,34,7.0000,9.1238,3.3536,6.5933,70.0000
1,27,male,master,5.6500,100,393,174,102,2.0000,8.8375,2.9081,4.1269,64.0000
2,31,male,bachelor,8.8700,181,231,595,140,1.0000,6.4867,2.8892,1.4291,65.2993
3,41,female,master,4.0500,94,268,18,121,4.0000,7.6005,3.0975,4.9955,80.0000
4,26,female,bachelor,13.0700,199,91,147,60,1.0000,5.1980,2.7861,9.4488,65.2993

In this case, we test the relationship between **sleep_hours** and **stress_level**.

Hypotheses:
- **H0**: There is no linear relationship between sleep hours and stress level.
- **H1**: There is a linear relationship between sleep hours and stress level.

Decision rule:
- If `p-value < 0.05`, reject **H0**.
- If `p-value >= 0.05`, fail to reject **H0**.

In [4]:
pearson_results = pd.DataFrame([
    pearson_test(df, 'sleep_hours', 'stress_level'),
])

pearson_results

,Variables,Correlation (r),p-value,Relationship,Decision,Conclusion
0,sleep_hours vs stress_level,-0.2917,0.0000,weak negative,Reject H0,The relationship between sleep_hours and stres...

## Conclusion
Based on the test result, the relationship between **sleep_hours** and **stress_level** is **statistically significant** because the p-value is less than `0.05`. The correlation is **negative**, which means that as sleep hours increase, stress level tends to decrease. Therefore, we **reject H0**. This means the negative relationship observed in EDA is **supported by statistical testing**.